In [3]:
import pandas as pd
import folium
from folium.plugins import HeatMap
from folium.plugins import MarkerCluster
import matplotlib.pyplot as plt

In [6]:
# Carregando dados tratados
df = pd.read_csv("acidentes_tratado.csv")
df.describe()

,predial1,queda_arr,feridos,feridos_gr,mortes,morte_post,fatais,auto,taxi,lotacao,...,outro,cont_vit,ups,patinete,idacidente,longitude,latitude,ano,mes,dia
count,6.515300e+04,69180.000000,69180.000000,69180.000000,69180.000000,69180.000000,69180.000000,69180.000000,69180.000000,69180.000000,...,69180.000000,69180.000000,69180.000000,69180.000000,69180.000000,58962.000000,58962.000000,69180.000000,69180.000000,69180.000000
mean,1.757127e+03,0.000405,0.450896,0.075224,0.003079,0.002616,0.005695,1.432278,0.014094,0.006418,...,0.000665,0.386817,2.591096,0.000564,714536.763328,-50.682287,-29.753715,2022.347759,6.576034,15.542874
std,6.835451e+03,0.020114,0.663515,0.286353,0.058202,0.051647,0.078818,0.761519,0.118612,0.080037,...,0.026876,0.487025,2.087772,0.024338,30955.581613,5.038592,2.958214,1.738484,3.539423,8.712201
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,190816.000000,-51.265854,-30.242610,2020.000000,1.000000,1.000000
25%,1.910000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,686524.750000,-51.212759,-30.065371,2021.000000,3.000000,8.000000
50%,7.660000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,704045.500000,-51.189453,-30.038010,2022.000000,7.000000,15.000000
75%,2.205000e+03,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.000000,5.000000,0.000000,741304.250000,-51.153946,-30.016948,2024.000000,10.000000,23.000000
max,1.097024e+06,1.000000,34.000000,5.000000,3.000000,2.000000,4.000000,10.000000,2.000000,2.000000,...,2.000000,1.000000,13.000000,2.000000,768506.000000,0.000000,0.000000,2202.000000,12.000000,31.000000